CREATE TABLE CONTINENTE (
	CONTINENTE_ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(100),
	AREA INT,
	POBLACION INT,
	DENSIDAD INT
);

CREATE TABLE PAIS (
	PAIS_ID INT NOT NULL PRIMARY KEY,
	CONTINENTE_ID INT NOT NULL REFERENCES CONTINENTE(CONTINENTE_ID),
	NOMBRE VARCHAR(100),
	AREA INT,
	POBLACION INT,
	DENSIDAD INT
);

CREATE TABLE REGION (
	REGION_ID INT NOT NULL PRIMARY KEY,
	PAIS_ID INT NOT NULL REFERENCES PAIS(PAIS_ID),
	NOMBRE VARCHAR(100),
	AREA INT,
	POBLACION INT,
	DENSIDAD INT
);

CREATE TABLE CIUDAD(
	CIUDAD_ID INT NOT NULL PRIMARY KEY,
	REGION_ID INT NOT NULL REFERENCES REGION(REGION_ID),
	NOMBRE VARCHAR(100),
	AREA INT,
	POBLACION INT,
	DENSIDAD INT
);

CREATE TABLE HISTORIAL(
	HISTORIAL_ID INT NOT NULL PRIMARY KEY,
	OPERACION VARCHAR(100),
	TABLA VARCHAR(100),
	REGISTRO VARCHAR(100),
	FECHA DATE,
	USUARIO VARCHAR(100)
);



CREATE TABLE ERRORES(
	ERRORES_ID INT NOT NULL PRIMARY KEY,
	OPERACION VARCHAR(100),
	ERROR VARCHAR(100),
	TABLA VARCHAR(100),
	FECHA DATE,
	USUARIO VARCHAR(100)
);

CREATE TABLE CATALOGOCONTINENTE(
	REF_IMG INT NOT NULL PRIMARY KEY,
	CONTINENTE_ID INT NOT NULL REFERENCES CONTINENTE(CONTINENTE_ID),
	IMAGEN BLOB
);

CREATE TABLE CATALOGOPAIS(
	REF_IMG INT NOT NULL PRIMARY KEY,
	PAIS_ID INT NOT NULL REFERENCES PAIS(PAIS_ID),
	IMAGEN BLOB
);

CREATE TABLE CATALOGOREGION(
	REF_IMG INT NOT NULL PRIMARY KEY,
	REGION_ID INT NOT NULL REFERENCES REGION(REGION_ID),
	IMAGEN BLOB
);

CREATE TABLE CATALOGOCIUDAD(
	REF_IMG INT NOT NULL PRIMARY KEY,
	CIUDAD_ID INT NOT NULL REFERENCES CIUDAD(CIUDAD_ID),
	IMAGEN BLOB
);

